### ISSUE TITLE
How easy would it be to adapt this software for Clojure programming language?

### ISSUE THREAD

**Issue by poiga** [viskell/viskell#421]
Sorry for the spam, but in your opinion is it possible to use any functional language? or any language at all? please share your opinion!

Thanks

**Comment by comonoidial** [comment]
As the name Viskell suggest this project started out with more visual representation of Haskell.
The current implementation is (unfortunately) very much coupled to all kinds of Haskell language details.

Conceptually we try to stay away from all specific syntactic constructs (forced upon us by the limitations of standard keyboards), and focus on the essential elements and abstractions of functional languages.
We could have started with any (immutable by default) functional language that can provide good contextual information on any (potentially incomplete) expression.
Exploiting good contextual information is essential for reducing the number of user actions required in a primarily touch based interface.
Haskell provides lots of reliable information in its typesystem, and some of us are experienced Haskell programmers, so that was our first choice.

I think Clojure as a language could be suitable for a similar programming environment, however it will have to rely more on live execution and reflection mechanisms for its contextual information and feedback.

For now we have no plans to support other languages, because we have still many (language independent) issues to solve first regarding user interaction, scalability, and program density.

**Comment by hangtwenty** [comment]
I would be very interested in something like Viskell for Clojure, too. My first side project would be to try [clojure-nltk](https://github.com/rplevy/clojure-nltk) with Viskell, see if I can realize my dream of a visual programming language for text generation.

Hearing everything you're saying, though, @comonoidial ... May just be a pipe dream to have 1 visual translation of multiple very different languages.

Subscribed to the thread in any case ;)

**Comment by andrewdavidmackenzie** [comment]
I'm interested in other languages too, but given the diversity of interest in languages, my suggestion would be to evolve towards language independence for the functions used in the visual blocks. The issue will be typing I imagine :-(

I want to look at describing a program visually, with functions in blocks, and then compiling and running in different ways - languages that have a compiler front-end that can produce LLVM IR would be my preferred route.
